accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

entry_test/urls.py
from django.urls import path
from . import views

app_name = 'entry_test'

urlpatterns	=	[

path('', views.index, name='home'),
path('1', views.index1, name='home1'),
]

firstapp/urls.py
from django.urls import path
from . import views

app_name = 'firstapp'

urlpatterns	=	[
path('', views.index),

]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), # new
    path('accounts/', include('django.contrib.auth.urls')),
    path('ll', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('firstapp.urls')), # new
    
    path('ent_test', include('entry_test.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

entry_test/models.py
from django.db import models


class Riddle(models.Model):
    riddle_text = models.TextField()
    
    def __str__(self): return self.riddle_text


class Option(models.Model):
    riddle = models.ForeignKey(Riddle, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    def __str__(self):
        if self.correct:
            value = "Correct"
        else:
            value = "Wrong"
        return "{} - ({}) [{}]".format(self.text, value, self.riddle.riddle_text)

firstapp/models.py
from django.db import models

# Create your models here.

accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

entry_test/views.py
from django.shortcuts import render
from random import shuffle
from django.http import HttpResponse
from . import models

def index(request):
    qs=models.Riddle.objects.all()
    ll=list(qs)
    shuffle(ll)
    ll_op=[]
    for topic in ll:
        rr = models.Riddle.objects.get(id=topic.id)
        rr_qs=rr.option_set.all()
        l_op=[]
        for op in rr_qs:
            l_op.append(op.text)
        shuffle(l_op)
        ll_op.append(l_op)
    remembrancies=ll
    remembrancies1=ll_op
    data = {"header": "Память", "remembrancies": remembrancies , "remembrancies1": remembrancies1}

    return render(request, "entry_test/index.html", context=data)
def index1(request):
    if request.method == "POST":
        name = request.POST
        ss=set()
        if len(name)==1:
            name1="Ваш заказ пуст"
        else:
            name1=''
            
            for ii in name:
                if ii != 'csrfmiddlewaretoken':
                    #name1+=(', '+ ii)
                    ss.add(ii)
            for ii in ss:
                name1+=(', '+ ii)
            name1=name1[2:]

        qs=models.Riddle.objects.all()
        ll=list(qs)
        s_op_n=set()
        name2=''
        for topic in ll:
            rr = models.Riddle.objects.get(id=topic.id)
            rr_qs=rr.option_set.all()
            for op in rr_qs:
                if op.correct:
                    s_op_n.add(op.text)
        for ii in s_op_n:
            name2+=(' '+ str(ii))
            #name2=name2[2:]

        if (len(ss & s_op_n) == len(s_op_n) and (len(ss | s_op_n) == len(s_op_n)) and len(ss)>0):
            #name3="Вы выполнили тест верно"
            data = {"res": "Вы выполнили тест верно","res1": 5}
        else:
            data = {"res": "Вы выполнили тест неправильно","res1": 0}
            #name3="Вы выполнили тест неправильно"

        return render(request, "entry_test/index1.html", context=data)
    
        #return HttpResponse("<h2>Ваш заказ:</h2><p> {0}!</p<p> {1}!</p> <p> {2}!</p>".format(name1,name2,name3))

firstapp/views.py
from django.shortcuts import render
 
def index(request):
    return render(request, "firstapp/index.html")



entry_test/templates/entry_test/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Django Forms</title>
</head>
<body>
   <strong>
    <h1>Входной тест</h1>
<table border="3">
<tr>
{% for person in remembrancies %}
<td> 
<pre>
<p>
{{person.riddle_text}}
 </p>
</pre>
</td>
{% endfor %} 
</tr>

<form action="{% url 'entry_test:home1' %}" method="post">
    {% csrf_token %}

<tr>
{% for person in remembrancies1 %}
<td> 
{% for per in person %}
     <input type="checkbox" name={{per}} />
        <label > {{per}}</label>
    <br>
    
{% endfor %} 
</td>
{% endfor %} 
</tr>
</table>

<table border="3">
<tr>


</table>
    <input type="submit" value="Ответ готов" />
</form>            

</strong>



</body>
</html>

entry_test/templates/entry_test/index1.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>входной тест</title>
</head>
<body>
    <h1>{{ res }}</h1>
{% if res1 %}
<a href="ll">to llout</a>
{% endif %}

</body>
</html>

firstapp/templates/firstapp/index.html
{% load bootstrap3 %}
	<!DOCTYPE html>
	<html lang="en">
	 <head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
	 <title>Learning Log</title>
	 {% bootstrap_css %}
{% bootstrap_javascript %}
	 </head>
	 
	 <body>

	 <h2>
<a href="ent_test">Register an account</a> to make
your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
Whenever you learn something new about a topic, make an entry
summarizing what you've learned.
</h2>
<h2>    Welcome to Django!  </h2>
<h2>     Тру-ля-ля          </h2>
<h2>    <a href="ent_test">на входной тест</a></h2>
    
</body>
</html>

firstapp/templates/firstapp/index1.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>входной тест</title>
</head>
<body>
    <h1>входной тест</h1>
    
    <a href="ll">to llout</a>
</body>
</html>

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}